import Okko from '../../assets/Okko.png';
import VkMusic from '../../assets/VkMusic.png';
import Wink from '../../assets/Wink.png';
import Yandex from '../../assets/Yandex.png';
import Ivi from '../../assets/ivi.png';
import Litres from '../../assets/Litres.png';
import Megogo from '../../assets/Megogo.png';
import Storytel from '../../assets/vendors.png';
import myBook from '../../assets/myBook.png';
import banner1 from '../../assets/service/1.png';
import banner2 from '../../assets/service/2.png';
import banner3 from '../../assets/service/3.png';
import banner4 from '../../assets/service/4.png';

export const services = [
  {
    id: '1234',
    name: 'Иви',
    cashback: '15',
    logo: Ivi,
    sum: '199',
    type: ['Кино'],
    description: 'ТВ, фильмы, сериалы',
  },
  {
    id: '5678',
    name: 'ЛитРес',
    cashback: '10',
    logo: Litres,
    sum: '299',
    type: ['Книги'],
    description: 'Книги, аудиокниги',
  },
  {
    id: '9012',
    name: 'MEGOGO',
    cashback: '20',
    logo: Megogo,
    sum: '249',
    type: ['Кино'],
    description: 'Фильмы, сериалы, мультфильмы',
  },
  {
    id: '3456',
    name: 'Storytel',
    cashback: '25',
    logo: Storytel,
    sum: '199',
    type: ['Книги'],
    description: 'Аудиокниги, книги на любой вкус',
  },
  {
    id: '7890',
    name: 'MyBook',
    cashback: '18',
    logo: myBook,
    sum: '179',
    type: ['Книги'],
    description: 'Электронные книги, журналы',
  },
  {
    id: '2345',
    name: 'Okko',
    cashback: '12',
    logo: Okko,
    sum: '299',
    type: ['Кино'],
    description: 'Фильмы, сериалы, мультфильмы',
  },
  {
    id: '6789',
    name: 'Яндекс.Плюс',
    cashback: '30',
    logo: Yandex,
    sum: '159',
    type: ['Прочее'],
    description: 'Сервисы Яндекса, кешбэк и акции',
  },
  {
    id: '0123',
    name: 'VkMusic',
    cashback: '15',
    logo: VkMusic,
    sum: '199',
    type: ['Музыка'],
    description: 'Песни, альбомы, плейлисты',
  },
  {
    id: '4567',
    name: 'Wink',
    cashback: '10',
    logo: Wink,
    sum: '299',
    type: ['Кино'],
    description: 'Фильмы, сериалы, мультфильмы',
    banner: [
      banner1,
      banner2,
      banner3,
      banner4,
      banner1,
      banner2,
      banner3,
      banner4,
    ],
    info: 'Подписка Wink представляет собой огромный каталог фильмов и сериалов, доступных без рекламы и в лучшем качестве. Здесь вы найдете широкий выбор контента для всех возрастов и вкусов, включая самые последние кинопремьеры и классические фильмы.',
    tariffs: [
      {
        id: 1,
        period: 1,
        discount: 0,
        price_per_month: 300,
        price_per_period: 300,
        periodName: 'monthly',
      },
      {
        id: 2,
        period: 3,
        discount: 3,
        price_per_month: 290,
        price_per_period: 870,
        periodName: 'quarterly',
      },
      {
        id: 3,
        period: 6,
        discount: 7,
        price_per_month: 280,
        price_per_period: 1680,
        periodName: 'semiannually',
      },
      {
        id: 4,
        period: 12,
        discount: 12,
        price_per_month: 250,
        price_per_period: 300,
        periodName: 'annually',
      },
    ],
  },
  {
    id: '2468',
    name: 'Netflix',
    cashback: '20',
    logo: 'Netflix',
    sum: '249',
    type: ['Кино'],
    description: 'Фильмы, сериалы, оригинальные контент',
  },
  {
    id: '8910',
    name: 'Spotify',
    cashback: '5',
    logo: 'Spotify',
    sum: '99',
    type: ['Музыка'],
    description: 'Стриминговая музыкальная платформа',
  },
  {
    id: '1112',
    name: 'HBO',
    cashback: '10',
    logo: 'HBO',
    sum: '199',
    type: ['Кино'],
    description: 'Фильмы, сериалы, оригинальный контент',
  },
  {
    id: '1314',
    name: 'Audible',
    cashback: '15',
    logo: 'Audible',
    sum: '149',
    type: ['Книги'],
    description: 'Аудиокниги',
  },
  {
    id: '1516',
    name: 'Apple Music',
    cashback: '5',
    logo: 'AppleMusic',
    sum: '149',
    type: ['Музыка'],
    description: 'Песни, альбомы, плейлисты',
  },
  {
    id: '1718',
    name: 'Google Play Books',
    cashback: '8',
    logo: 'GooglePlayBooks',
    sum: '199',
    type: ['Книги'],
    description: 'Электронные книги',
  },
  {
    id: '1920',
    name: 'Amazon Prime Video',
    cashback: '10',
    logo: 'AmazonPrimeVideo',
    sum: '199',
    type: ['Кино'],
    description: 'Фильмы, сериалы, оригинальный контент',
  },
];
